<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Mediator.SourceGenerator" Version="3.1.0-rc.1">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\HubManagement.Application\HubManagement.Application.csproj" />
      <ProjectReference Include="..\HubManagement.Domain\HubManagement.Domain.csproj" />
      <ProjectReference Include="..\HubManagement.Infrastructure\HubManagement.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Endpoints\V1\" />
    </ItemGroup>

</Project>
