<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Features\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\HubManagement.BuildingBlock.Core\HubManagement.BuildingBlock.Core.csproj" />
      <ProjectReference Include="..\HubManagement.Domain\HubManagement.Domain.csproj" />
    </ItemGroup>

</Project>
